{
 "title": "OTEL Golang App Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "env", "query": { "query": "label_values(env)" } },
   { "name": "route", "query": { "query": "label_values(http_route)" } },
   { "name": "http_method", "query": { "query": "label_values(http_method)" } }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  up[$__range]\n) * 100\n",
     "legendFormat": "Instance"
    }
   ]
  },
  {
   "title": "Top requested routes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(\n  3,\n  sum by (http_route) (\n    max_over_time(\n      http_server_metrics_seconds_count{\n        http_method!~\"OPTIONS\"\n      }[$__range]\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  max_over_time(\n    http_server_metrics_seconds_count{\n      env=~\"${env}\", \n      http_route=~\"${route}\", \n      http_method!~\"OPTIONS\", \n      http_method=~\"${http_method}\", \n    }[$__range]\n  )\n) by (http_method, http_route)\n",
     "legendFormat": "x"
    },
    {
     "expr": "sum(\n  max_over_time(\n    http_server_metrics_seconds_count{\n      env=~\"${env}\", \n      http_route=~\"${route}\", \n      http_method!~\"OPTIONS\", \n      http_method=~\"${http_method}\", \n      http_status_code=~\"2..\"\n    }[$__range]\n  )\n) by (http_method, http_route)\n",
     "legendFormat": "x"
    },
    {
     "expr": "sum(\n  max_over_time(\n    http_server_metrics_seconds_count{\n      env=~\"${env}\", \n      http_route=~\"${route}\", \n      http_method!~\"OPTIONS\", \n      http_method=~\"${http_method}\", \n      http_status_code=~\"3..\"\n    }[$__range]\n  )\n) by (http_method, http_route)\n",
     "legendFormat": "x"
    },
    {
     "expr": "sum(\n  max_over_time(\n    http_server_metrics_seconds_count{\n      env=~\"${env}\", \n      http_route=~\"${route}\", \n      http_method!~\"OPTIONS\", \n      http_method=~\"${http_method}\", \n      http_status_code=~\"4..\"\n    }[$__range]\n  )\n) by (http_method, http_route)\n",
     "legendFormat": "x"
    },
    {
     "expr": "sum(\n  max_over_time(\n    http_server_metrics_seconds_count{\n      env=~\"${env}\", \n      http_route=~\"${route}\", \n      http_method!~\"OPTIONS\", \n      http_method=~\"${http_method}\", \n      http_status_code=~\"5..\"\n    }[$__range]\n  )\n) by (http_method, http_route)\n",
     "legendFormat": "x"
    },
    {
     "expr": "sum(\n    rate(\n        http_server_metrics_seconds_sum{\n            env=~\"${env}\",  \n            http_route=~\"${route}\", \n            http_method!~\"OPTIONS\",\n            http_method=~\"${http_method}\",\n        }[$__rate_interval]) * $__interval\n    ) by (env, http_method, http_route)",
     "legendFormat": "x"
    },
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_metrics_seconds_sum{\n                env=~\"${env}\", \n                http_route=~\"${route}\", \n                http_method!~\"OPTIONS\",\n            http_method=~\"${http_method}\",\n            }[$__rate_interval])\n        ) by(env, http_method, http_route) \n    / \n    sum(\n        rate(\n            http_server_metrics_seconds_count{\n                env=~\"${env}\", \n                http_route=~\"${route}\", \n                http_method!~\"OPTIONS\",\n            http_method=~\"${http_method}\",\n            }[$__rate_interval])\n        ) by(env, http_method, http_route) >= 0\n) OR on() vector(0)",
     "legendFormat": "x"
    }
   ]
  },
  {
   "title": "Api request duration",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  rate(http_server_metrics_seconds_sum{\n    env=~\"${env}\", \n    http_route=~\"${route}\", \n    http_method!~\"OPTIONS\",\n    http_method=~\"${http_method}\"\n  }[$__rate_interval])\n) by (env, http_route, http_method)\n/\navg(\n  rate(http_server_metrics_seconds_count{\n    env=~\"${env}\", \n    http_route=~\"${route}\", \n    http_method!~\"OPTIONS\",\n    http_method=~\"${http_method}\"\n  }[$__rate_interval])\n) by (env, http_route, http_method)\n",
     "legendFormat": "{{http_method}} {{http_route}}"
    }
   ]
  },
  {
   "title": "Database latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(\n      db_sql_client_latency_milliseconds_bucket[$__range]\n    )\n  )\n)",
     "legendFormat": "Database latency"
    }
   ]
  },
  {
   "title": "Success | Fail rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(\n    max_over_time(\n      http_server_metrics_seconds_count{\n        env=~\"${env}\",\n        http_route=~\"${route}\",\n        http_method=~\"${http_method}\",\n        http_status_code=~\"2..|3..\",\n        http_method!~\"OPTIONS\"\n      }[$__range]\n    ),\n    \"status\",\n    \"Success\",\n    \"\",\n    \"\"\n  )\n  or\n  label_replace(\n    max_over_time(\n      http_server_metrics_seconds_count{\n        env=~\"${env}\",\n        http_route=~\"${route}\",\n        http_method=~\"${http_method}\",\n        http_status_code=~\"4..|5..\",\n        http_method!~\"OPTIONS\"\n      }[$__range]\n    ),\n    \"status\",\n    \"Fail\",\n    \"\",\n    \"\"\n  )\n)\n/ on() group_left()\nsum(\n  max_over_time(\n    http_server_metrics_seconds_count{\n      env=~\"${env}\",\n      http_route=~\"${route}\",\n      http_method=~\"${http_method}\",\n      http_method!~\"OPTIONS\"\n    }[$__range]\n  )\n)\n* 100",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}